### ISSUE TITLE
Removing the ACF Menu by default

### ISSUE THREAD

**Issue by ghost** [Brugman/acf-agency-workflow#4]
Hi, 
just a suggestion here.

**_The Field Groups backend menu link has been removed on non-local environments to deter use. The page is still available however, if you visit the URL directly._**

My opinion (prbably not worth much as im not half as talented a dev as you) is that I think this shouldn't be enforced. ACF already has an option for this.

**Comment by Brugman** [comment]
I've enforced this because my clients often have shared hosting without SSH access, or if they have SSH, the server won't have git on it. So then if I, a coworker, or the client by accident makes a field on the staging or production environment, then we have to copy the json, or export/import the FG, to get the FG into our local env so we can commit it. With the menu item gone I hope everyone realizes they're on the wrong env before they make the field group. If they still want to go to the FG page, they can add `/wp-admin/edit.php?post_type=acf-field-group` to the url.

That's the long explanation from my POV. A bit too long for the README I thought.

But I'm interested, why would you want to access the FG page on non-local?

And what's the ACF option you mentioned? The hook, or is there another?

**Comment by ghost** [comment]
I like having FG available just for the sake of quickly looking at fields if i need to, when im away from my local env or dont have access to my repo. 

Sometimes its quicker for me to export a FG to use on another project rather than start up a local env just to access a FG. 

I guess having the option of it being available is better than remembering to turn on local env on each instance of WP that i have. 

I think another (better IMHO) option would be to have a message on the ACF page to remind users that they are working on a live environment.

on live environments, i disable the backend for all users that are not admin using the ACF filter found here:

https://www.advancedcustomfields.com/resources/how-to-hide-acf-menu-from-clients

if a client is an admin, then i disable access to only superadmins (myself and any other devs) but this is a rare case.

I have the code for hiding ACF from admins embedded in our framework.

I guess i want to be in control and decide wether its hidden or not, rather than it being forced on me lol. 
In this instance i will just comment out your code for hiding it. 

Thanks for your work on this plugin. It's great, ive forwarded to a few other devs who live off ACF :)

**Comment by Brugman** [comment]
Hmm. I've come up with more arguments _against_ the current approach.

1. Hiding the menu item does not just hide "Field Groups", it also hides the "Tools" and "Updates" items underneath. Tools' Export could be useful., and "Updates" can be very useful if you need to put in your license.

2. Didn't expect this: On non-local you can reach Field Groups with the right URL, but Tools and Updates is blocked even if you have the URL!

3. I have another plugin (not yet on GitHub) that hides stuff so business owners that are new to WordPress don't get confused by 100 options and menu items, when they only need to use 5 on a daily basis. Hiding the ACF menu could be a very good fit for that plugin.

I'm going to try a warning message, and give this more thought.

**Comment by Brugman** [comment]
b4b76d96d9e9544032f6364173d3d31e8686f6aa / v1.2.0 has these changes.

**Comment by ghost** [comment]
your arguments are better than mine. Thank you!
